name: CICD 
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  CICD:
    uses: lbasg/cicd/.github/workflows/main.yml@main
    with: 
      technology: ${{ vars.APP_TECH }}
      application: ${{ vars.APP_NAME }}
