name: CICD 
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  CICD:
    uses: lbasg/cicd/.github/workflows/main.yml@validate-Iberdrolafile
    with: 
      repository: ${{ github.repository }}

